services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: consumer-auth-service
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      APP_URL: "http://localhost:8080"
      JWT_VALIDITY_TIME: "2"
      JWT_TYPE_TIME: "hours"
      PRIVATE_KEY_PASSPHRASE: "${PRIVATE_KEY_PASSPHRASE}"
      DATABASE_HOST: "db"
      DATABASE_PORT: "3306"
      DATABASE_NAME: "hire_now"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "root"
      DATABASE_CHARSET: "utf8mb4"
    depends_on:
      - redis
      - db

  redis-listener:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-listener
    command: php public/redis_listener.php
    volumes:
      - .:/var/www/html
    depends_on:
      - redis
    environment:
      DATABASE_HOST: "db"
      DATABASE_PORT: "3306"
      DATABASE_NAME: "hire_now"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "root"
      DATABASE_CHARSET: "utf8mb4"

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"

  db:
    image: mysql:8.0
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "hire_now"
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: ["--init-file", "/docker-entrypoint-initdb.d/init.sql"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-proot"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 5s

volumes:
  db_data: